package peliRekisteri.test;
// Generated by ComTest BEGIN
import peliRekisteri.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.02 00:07:04 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KategoriatTest {



  // Generated by ComTest BEGIN
  /** testIterator188 */
  @Test
  public void testIterator188() {    // Kategoriat: 188
    Kategoriat kattit = new Kategoriat(); 
    Kategoria fps21 = new Kategoria(2); kattit.lisaa(fps21); 
    Kategoria fps11 = new Kategoria(1); kattit.lisaa(fps11); 
    Kategoria fps22 = new Kategoria(2); kattit.lisaa(fps22); 
    Kategoria fps12 = new Kategoria(1); kattit.lisaa(fps12); 
    Kategoria fps23 = new Kategoria(2); kattit.lisaa(fps23); 
    Iterator<Kategoria> i2 = kattit.iterator(); 
    assertEquals("From: Kategoriat line: 200", fps21, i2.next()); 
    assertEquals("From: Kategoriat line: 201", fps11, i2.next()); 
    assertEquals("From: Kategoriat line: 202", fps22, i2.next()); 
    assertEquals("From: Kategoriat line: 203", fps12, i2.next()); 
    assertEquals("From: Kategoriat line: 204", fps23, i2.next()); 
    try {
    assertEquals("From: Kategoriat line: 205", fps12, i2.next()); 
    fail("Kategoriat: 205 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int pnrot[] = { 2,1,2,1,2} ; 
    for (Kategoria kat : kattit) {
    assertEquals("From: Kategoriat line: 210", pnrot[n], kat.getPelinNro()); n++; 
    }
    assertEquals("From: Kategoriat line: 215", 5, n); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaKategoriat232 */
  @Test
  public void testAnnaKategoriat232() {    // Kategoriat: 232
    Kategoriat kattit = new Kategoriat(); 
    Kategoria fps21 = new Kategoria(2); kattit.lisaa(fps21); 
    Kategoria fps11 = new Kategoria(1); kattit.lisaa(fps11); 
    Kategoria fps22 = new Kategoria(2); kattit.lisaa(fps22); 
    Kategoria fps12 = new Kategoria(1); kattit.lisaa(fps12); 
    Kategoria fps23 = new Kategoria(2); kattit.lisaa(fps23); 
    Kategoria fps51 = new Kategoria(5); kattit.lisaa(fps51); 
    List<Kategoria> loytyneet; 
    loytyneet = kattit.annaKategoriat(3); 
    assertEquals("From: Kategoriat line: 244", 0, loytyneet.size()); 
    loytyneet = kattit.annaKategoriat(1); 
    assertEquals("From: Kategoriat line: 246", 2, loytyneet.size()); 
    assertEquals("From: Kategoriat line: 247", true, loytyneet.get(0) == fps11); 
    assertEquals("From: Kategoriat line: 248", true, loytyneet.get(1) == fps12); 
    loytyneet = kattit.annaKategoriat(5); 
    assertEquals("From: Kategoriat line: 250", 1, loytyneet.size()); 
    assertEquals("From: Kategoriat line: 251", true, loytyneet.get(0) == fps51); 
  } // Generated by ComTest END
}