package peliRekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import peliRekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.02 00:06:55 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KategoriaTest {



  // Generated by ComTest BEGIN
  /** 
   * testClone121 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone121() throws CloneNotSupportedException {    // Kategoria: 121
    Kategoria kat = new Kategoria(); 
    kat.parse("   2   |  10  |   Csgo  |"); 
    Kategoria kopio = kat.clone(); 
    assertEquals("From: Kategoria line: 126", kat.toString(), kopio.toString()); 
    kat.parse("   1   |  11  |   Csgo  |"); 
    assertEquals("From: Kategoria line: 128", false, kopio.toString().equals(kat.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi157 */
  @Test
  public void testRekisteroi157() {    // Kategoria: 157
    Kategoria fps1 = new Kategoria(); 
    assertEquals("From: Kategoria line: 159", 0, fps1.getTunnusNro()); 
    fps1.rekisteroi(); 
    Kategoria fps2 = new Kategoria(); 
    fps2.rekisteroi(); 
    int n1 = fps1.getTunnusNro(); 
    int n2 = fps2.getTunnusNro(); 
    assertEquals("From: Kategoria line: 165", n2-1, n1); 
  } // Generated by ComTest END
}